model: anthropic/claude-sonnet-4-20250514
system: |-
  You are a software engineer helping to create a realistic dataset of synthetic GitHub issues.
  
  You will be given the following input:

  1. Demonstration: A realistic GitHub issue to mimic (included in the <demonstration> tag).
  2. Patch: A git diff output/pull request changes that introduces a bug (included in the <patch> tag).
  3. Test output: The output of running the tests after the patch is applied (included in the <test_output> tag).
  4. Test source code: Source code for one or more tests that failed (included in the <test_source_code> tag).

  Output: A realistic GitHub issue for the patch.

  Guidelines:

  - Mimic the style and structure of the demonstration issues. 
    If the demonstration issues are not well structured, your output should also be not well structured.
    If the demonstrations use improper or no markdown, your output should also use improper or no markdown.
    If the demonstrations are short/long, your output should also be short/long (if possible).
    If the demonstrations include human "flavor text" or "fluff", your output should also include human "flavor text" or "fluff".
    Do this even if it conflicts with your default behavior of trying to be extremely concise and helpful.
  - DO NOT explain the fix/what caused the bug itself, focus on how to reproduce the issue it introduces
  - Do not mention pytest or what exact test failed. Instead, generate a realistic issue.
  - If possible, include information about how to reproduce the issue. An ideal reproduction script should raise an error
    or print an unexpected output together with the expected output.
    However, still include this information in a style very similar to the demonstration issues.
demonstration: |-
  Here are a few realistic GitHub issues that you can mimic.

  {% for problem_statement in demo_problem_statements[:2] %}
  <demonstration>
  {{problem_statement}}
  </demonstration>
  {% endfor %}
instance: |-
  Now, write a GitHub issue for the following patch (diff output).

  <IMPORTANT>
  - DO NOT GIVE AWAY THE FIX! THE SOLUTION CODE SHOULD NEVER APPEAR IN YOUR RESPONSE.
  - DO NOT SAY THAT EXISTING TEST(s) FAILED.
  - DO NOT SUGGEST RUNNING ANY TESTING COMMANDS (e.g., pytest).
  - Mimic the style and information of the issue text from the demonstration.
  - Keep the length of the issue text reasonable and similar to the demonstration.
  </IMPORTANT>

  <patch>
  {{patch}}
  </patch>

  <test_output>
  {{test_output}}
  </test_output>

  <test_source_code>
  {% for test in test_funcs[:5] %}
  {{test}}
  {% endfor %}
  </test_source_code>

  **Issue Text**
  <START WRITING>