repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version
  rev: v0.14.11
  hooks:
    # Run the linter
    - id: ruff
      # Only fix newly changed lines
      args: [ --fix, --diff ]
    # Run the formatter
    - id: ruff-format
      args: [ --exclude=notebooks ]