site_name: SWE-smith Documentation
site_url: https://swe-smith.com/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  logo: assets/swesmith_logo.png
  favicon: assets/swesmith_logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      # primary: black # override in custom.css
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      # primary: black # override in custom.css
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - navigation.footer
    - content.code.copy
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - content.code.annotate
markdown_extensions:
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.html
  - Getting started:
    - getting_started/index.md
    - Installation: getting_started/installation.md
    - Assets: getting_started/assets.md
    - Quickstart: getting_started/quickstart.md
  - Tutorials:
    - guides/index.md
    - Build Environments: guides/env_construction.md
    - Create Instances: guides/create_instances.md
    - Validation & Evaluation: guides/harnesses.md
    - Generate Issue Text: guides/issue_gen.md
    - Rate Difficulty: guides/difficulty_rating.md
    - Train SWE-agents: guides/train_swe_agent.md
  - Miscellaneous:
    - Build Python Environments: guides/env_construction_py.md
plugins:
   - glightbox
   - search
   - include-markdown
   - mike:
      canonical_version: latest
      version_selector: true
   - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ['swesmith']
          options:
            merge_init_into_class: true
            summary: false
            show_root_heading: true
            heading_level: 2
            docstring_style: google
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
              - griffe_pydantic:
                  schema: false
repo_url: https://github.com/SWE-bench/SWE-smith
repo_name: SWE-bench/SWE-smith
edit_uri: edit/main/docs/
extra_css:
  - css/custom.css
  - css/mkdocstrings.css
  - css/bubbles.css
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-T5P2NYGJYR